# Generated by Django 4.2.7 on 2023-12-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='category_image',
            field=models.ImageField(default='img/cat-1.jpg', upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='img/cat-1.jpg', upload_to='productImage/'),
        ),
    ]
